---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-smoke-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-smoke-test-pod
  namespace: default
spec:
  containers:
    - name: test
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          echo "Starting smoke test..."
          echo "Writing test data to /data/test.txt"
          date > /data/test.txt
          echo "Test data written successfully"
          echo "Verifying test data..."
          cat /data/test.txt
          echo "Smoke test completed successfully!"
          sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: csi-smoke-test-pvc
